### ISSUE TITLE
Move all template files to `templates/ios/`

### ISSUE THREAD

**Issue by Ashton-W** [CocoaPods/pod-template#103]
I think it would be good to move all the template files to the `templates/ios/` directory to make it clearer what files are part of the generator and which are part of the template and resulting project.

This will also make it easier to select from many different templates under `templates/`.

I have made this change in my fork for example.
https://github.com/Ashton-W/pod-template-framework/tree/master/templates/ios

I'll open a PR if you are interested.

**Comment by orta** [comment]
think this make sense, but given the work I've been doing on swift support, not something I want large scale merge conflicts with ATM

**Comment by orta** [comment]
#105 is almost in now

**Comment by fulldecent** [comment]
Perhaps this is closable now.
