### ISSUE TITLE
Swift code not accessible in test target when there is no demo application 

### ISSUE THREAD

**Issue by jwutke** [CocoaPods/pod-template#110]
When creating a pod without a demo application, the code from the Swift files does not end up accessible from the test target. When a demo application is included, there is no issue. I have not tried with an Obj-C project yet.

```
pod lib create test

...

What language do you want to use?? [ ObjC / Swift ]
 > Swift

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Quick / None ]
 > Quick

Would you like to do view based testing? [ Yes / No ]
 > No

Running pod install on your new library.

...
```

Put this code into ReplaceMe.swift.
```
public let test = "test"
```

Try to use the variable in Tests.swift and you get this error.
```
Swift Compiler Error
Use of unresolved identifier test
```

**Comment by orta** [comment]
I see the problem, the tests have the same framework id as the pod, it's the same problem we were seeing with the app itself.

**Comment by orta** [comment]
![screen shot 2015-05-28 at 06 01 49](https://cloud.githubusercontent.com/assets/49038/7857553/2e21e008-04ff-11e5-947d-27b60dbf332b.png)
 
Got it
