### ISSUE TITLE
`pod lib create` creates tests outside of tested library module

### ISSUE THREAD

**Issue by nikita-leonov** [CocoaPods/pod-template#114]
Moved conversation from here — https://github.com/CocoaPods/CocoaPods/issues/3633

Currently `pod lib create` for Swift project creates all tests as separate library. Which was fine for ObjC project, but not very comfy for Swift as we can not tests internal methods anymore that are visible only within module. 

Public interfaces could be much smaller than an actual internal implementation, so resulting tests looks like a functional / integration tests rather than unit-tests. For some libraries it may work, for some not. 

Would it be better to provide an option to decide in a wizard where tests should be created and keep it up to developer to decide?

**Comment by orta** [comment]
This isn't really possible unless https://github.com/CocoaPods/Core/pull/232 happens and Pods can define their test files, you can't work with dev pods because they always create a separate framework. 

Even then, I'm not sure I'd want to support this, we started out building in this technique in [Eidolon](https://github.com/artsy/eidolon) + [Moya](http://cocoapods.org/pods/Moya), but switched after a month or so and have had little problems in testing our libraries since then.

That said, I've not done enough swift nowadays to really feel like I have a strong grip on what's happening. Will /cc in some opinions

**Comment by segiddins** [comment]
My own opinion is that if your internals need to be tested, the belong as public members of a separate framework.

**Comment by modocache** [comment]
The fact that Swift only allows us to test public interfaces is a departure from Objective-C, but resembles other languages with explicit access modifiers, such as Java. In languages such as these, a prominent school of thought exists that [only public interfaces should be tested](http://stackoverflow.com/a/440802). I align with this school of thought, and it seems the `pod lib create` behavior does as well.

> Public interfaces could be much smaller than an actual internal implementation, so resulting tests looks like a functional / integration tests rather than unit-tests.

I agree that this is something we will have to be dilligent to avoid when writing unit tests in Swift. On the other hand, some would say that these tests end up being more behavioral.

> My own opinion is that if your internals need to be tested, the belong as public members of a separate framework.

Unfortunately, end users will have to end up linking two frameworks with this approach. I agree that I'd rather use this method than including production code in my test target.

**Comment by nikita-leonov** [comment]
I am fully on your side regarding ObjC and Java, however both of this languages does not have access modifiers with semantics like Swift. It is a bad practice to tests something with `private` modifier as it brakes encapsulation, meanwhile I would be happy to have an option to test internals.

The way how cocoa pods suggests to do testing for Swift brings new requirements in a way how TDD should be executed. I will review an option with braking down into multiple libraries but not sure this'll be a good option. It will create a bunch of nano-libraries from my micro-enough-library.

I think it makes sense to keep this issue open for a little bit to collect more opinions. Anyway I do not have any personal attachments to one way or another and would be happy to develop tests for libs in most efficient way as soon as I will clarify one.

**Comment by nikita-leonov** [comment]
Actually looking more into Java and talking with dev I found there is `package-private` available which is similar to `internal` in Swift. Moreover there is similar suggestions regarding  approach to testing of package-private methods https://weblogs.java.net/blog/2005/07/19/package-scoping-and-unit-testing 

My point that having such a high entry point for tests will make tests hard to write, fragile and hard to  maintain. I do see a need in both options. Where functional, long-running high level tests testing public methods, while fast-running unit-tests testing internals. It will be also in line with Google best practices of tests separation between various buckets depends on a time of execution. However having multiple targets for tests may bring additional confusion for an end consumer who are not sophisticated in testing.

**Comment by nikita-leonov** [comment]
So here are formal requirements that makes sense from my point of view:
* As a developer of a module I integrate my classes into one solution by using `internal` and `public` methods, so I for sure want be able to test them. This will allow me to provide full test coverage by granular, fast performing tests that easy to maintain and develop.
* As a user of a module I want to be sure that library that I am using is stable and covers all my needs, so I want to see tests that covers all my use-cases. This will give me a level of confidence and satisfaction in solution candidate.

This justifies a need for testing of both internal and public methods of modules. Would be glad to review other points of view.

**Comment by ashfurrow** [comment]
I strongly feel that we should keep things as-is. Testing public methods is sufficient to ensure stability and test coverage. There's no material benefit to being able to call internal methods in a test that no one can call from outside the framework anyway.

**Comment by ashfurrow** [comment]
Besides, it's only a default. CocoaPods isn't preventing you from doing whatever you like – it's just not encouraging testing internals.

**Comment by nikita-leonov** [comment]
Here is some real life examples:
* Internal structure — https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/ReactiveCocoa/Swift/Bag.swift
* Test for an internal structure — https://github.com/ReactiveCocoa/ReactiveCocoa/blob/swift-development/ReactiveCocoaTests/Swift/BagSpec.swift

With a current temple such tests and resulting test coverage would be hard to achieve. I think I would be able to find more and more examples like this, but this one should be enough to highlight that situation is common.

**Comment by nikita-leonov** [comment]
@ashfurrow I agree that developer is free to do whatever he want with his project. However I am trying to find a way that will provide developers a common ground for testing implementations that takes into account Swift specific, as well as emphasis best practices. 

I know why testing of private methods in classes is bad, I do not have an answer why testing of internal methods in modules is bad. I see testing of internal methods as an optimal way for developers to ensure the correctness of implementation.

**Comment by neonichu** [comment]
@nikita-leonov  I'm having a hard time understanding what your actual proposal for pod-template is. In the RAC example you are giving, I cannot see the `BagSpec.swift` file being included in any target at all - how exactly is it tested?

**Comment by ashfurrow** [comment]
I guess this is where we differ. I don't think unit tests are to test the correctness of the implementation; they only test the correctness of the behaviour.

**Comment by nikita-leonov** [comment]
@neonichu This is good question to ask. I do not know how exactly they run tests in RAC, what I know that they do implement tests for internal classes and structures. I also noticed they are do not have tests for internal functionality included into any of test targets. 

The only way for internals to be tested is to be included into the same module as tests. My suggestion is to have a test bundle that contains both tests and sources that need to be tested.

**Comment by segiddins** [comment]
@nikita-leonov which you're totally welcome to do. I just don't think that needs to be the default with _this particular_ `pod lib create` template.

**Comment by nikita-leonov** [comment]
@ashfurrow my bad, I do agree that it is not about how solution implemented but how it is actually works.  As for today I agree with the @segiddins point about external framework with its own set of tests. While sometimes it is too much overhead, on a bigger solutions it should be the the right way to go. Also your and @segiddins initial point about modification of default template is also correct.

**Comment by nikita-leonov** [comment]
There is actually a small chance that Apple will change behavior and tests would be automatically a part of application module, but not a separate one. Here is a note from Xcode release notes about access modifiers:
"A limitation of the access control system is that unit tests cannot interact with the classes and methods in an application unless they are marked public. This is because the unit test target is not part of the application module.!" http://mazur.me/SwiftInFlux/docs/beta4.pdf

**Comment by nikita-leonov** [comment]
I check how Maven in Java world is doing this, apparently they include sources and tests into the same package for the purpose of testing package scope classes.

**Comment by orta** [comment]
Yeah, it'd be interesting to see if  https://github.com/CocoaPods/Core/pull/232 makes it so dev pods include a test target too

**Comment by nikita-leonov** [comment]
Here is some new information from recent Xcode 7 release notes — "Testability. Write tests of Swift 2.0 frameworks and apps with access to all your public and internal routines."

It could be that this @testable will make this issue totally redundant.

**Comment by nikita-leonov** [comment]
And now this issue is finally closed-closed :) 

"Testability. Tests of Swift 2.0 frameworks and apps are written without having to make internal routines public. Use @testable import {ModuleName} in your test source code to make all public and internal routines usable. The app or framework target needs to be compiled with the "Enable Testability" build setting on. The "Enable Testability" build setting should only be used in your Debug configuration, as it will prohibit optimizations that depend on not exporting internal symbols from the app or framework. (17732115)"

Thank you very much gents, I am happy that we achieved what needed with zero changes in code. 

As for the changes does it make sense to import libs into tests as \@testable now or it will stay as is?
