### ISSUE TITLE
Can't reference Swift class from Obj-C file

### ISSUE THREAD

**Issue by diamondsky** [CocoaPods/pod-template#115]
Good day,

I've ran into an issue that I don't know how to address. If I'm creating an `@objc` class or protocol in one swift file, and then trying to use it in obj-c file within the same pod, the compilation fails with `Cannot find declarations for 'ProtocolName'`, or `Unknown type name 'ClassName'`. 

I've created a demo project to illustrate that: https://github.com/diamondsky/ObjcSwiftTest

Maybe I should enable some build setting? Really weird bug.

**Comment by neonichu** [comment]
This is an issue with your Pod, not with the template. To reference the Swift part of a framework from Objective-C, you need to import the generated `*-Swift.h` header. In addition to that, types which are to be used from ObjC need to be `public`, otherwise they will not be forward declared in the compatibility header.

```diff
diff --git a/Pod/Classes/MyObjcClass.h b/Pod/Classes/MyObjcClass.h
index 2e7ceae..ed7a621 100644
--- a/Pod/Classes/MyObjcClass.h
+++ b/Pod/Classes/MyObjcClass.h
@@ -3,6 +3,7 @@
 //
 
 #import <Foundation/Foundation.h>
+#import <ObjcSwiftTest/ObjcSwiftTest-Swift.h>
 
 @interface MyObjcClass : NSObject <MySwiftDelegate>
 
diff --git a/Pod/Classes/MySwiftClass.swift b/Pod/Classes/MySwiftClass.swift
index 1425252..e78b5bd 100644
--- a/Pod/Classes/MySwiftClass.swift
+++ b/Pod/Classes/MySwiftClass.swift
@@ -4,7 +4,7 @@
 
 import UIKit
 
-@objc protocol MySwiftDelegate {
+@objc public protocol MySwiftDelegate {
     func dummy()
 }
 ```

**Comment by diamondsky** [comment]
Hi Boris,
Thank you so much for the advice, it helped! I've been trying all sorts of things, but every time I imported swift-header with `#import "ObjcSwiftTest-Swift.h"` it failed. Angled brackets work. Amazing.

Thank you once again.
