### ISSUE TITLE
GITHUB_USERNAME and TWITTER_USERNAME are not set 

### ISSUE THREAD

**Issue by kostiakoval** [CocoaPods/pod-template#125]
`pod lib create`
the `Pod.podspec` contains  `GITHUB_USERNAME` and  `TWITTER_USERNAME`.

The user needs to replace them manually.
It would be great we it was possible to set those 2 variables during pod creation and store it some somewhere so user don't need to change it every time.

**Comment by fulldecent** [comment]
Please break this to two different issues:

 * Update configurator to ask questions for these two variables (keep in #125)
 * Create caching system to save user preferences somewhere (make new issue)

Here is scope of work to do this issue:

 - [ ] https://github.com/CocoaPods/pod-template/blob/f62261cb8e5692ae6e46c8a3922ac347837df040/setup/ProjectManipulator.rb#L21-L27
 - [ ] https://github.com/CocoaPods/pod-template/blob/8d4bff2b6d48d4e4af5fcd6098765e20f4286cbd/setup/TemplateConfigurator.rb#L119-L131
 - [ ] https://github.com/CocoaPods/pod-template/blob/f62261cb8e5692ae6e46c8a3922ac347837df040/setup/MessageBank.rb#L77-L88
 - [ ] https://github.com/CocoaPods/pod-template/blob/8d4bff2b6d48d4e4af5fcd6098765e20f4286cbd/setup/TemplateConfigurator.rb#L119-L131

I will make a PR if there are more +1's here.

**Comment by malhal** [comment]
The github username is put in the license file so there is absolutely no reason why it isn't put in the podsepc file. I'd consider that one a bug.

Personally I would like the Twitter username set to the Github username since in my case they are the same, but I don't mind having to enter that one manually.

**Comment by malhal** [comment]
Simple fix, rename <GITHUB_USERNAME> to ${USER_NAME}

**Comment by fulldecent** [comment]
Looks good. Please create pull request.

**Comment by jugutier** [comment]
github should be addressed when this is merged https://github.com/CocoaPods/pod-template/pull/200
