### ISSUE TITLE
The Author name and author git username should be different

### ISSUE THREAD

**Issue by kostiakoval** [CocoaPods/pod-template#126]
My config

```
git config --list
user.name=Kostiantyn Koval
user.email=konstantin.koval1@gmail.com
```

After creating a pod `pod lib create` the README.md uses the `user.name` for the travis setup, but should use `github username` instead. 

`[![CI Status](http://img.shields.io/travis/Kostiantyn Koval/TestMeMe1234.svg?style=flat)](https://travis-ci.org/Kostiantyn Koval/TestMeMe1234)`

This is correct
`[![CI Status](http://img.shields.io/travis/kostiakoval/TestMeMe1234.svg?style=flat)](https://travis-ci.orgkostiakoval/TestMeMe1234)`

**Comment by segiddins** [comment]
@kostiakoval a PR for this would be excellent!

**Comment by fulldecent** [comment]
@kostiakoval Is there a way to get the github username programmatically?

Recommending close if not possible

**Comment by jugutier** [comment]
@kostiakoval this has been added to the repo. Please verify and close this issue if addressed.

-J

**Comment by dnosk** [comment]
Still experiencing this issue. It pulls in an old email as my copyright name and the podspec uses that as the github username -> https://github.com/XXX/Example.git

**Comment by jugutier** [comment]
Hi Daniel,

We set this up so that it'll get your github info from keychain, try
logging into github on safari and -- when prompted, update your
user/password.

Alternative you can set GIT_COMMITER_EMAIL environment variable before the
pod lib create command.

Let me know how that goes.

**Comment by dnosk** [comment]
That works, thanks @jugutier
