### ISSUE TITLE
Could CocoaPods targets use Debug-iphoneos instead of Debug?

### ISSUE THREAD

**Issue by pinxue** [CocoaPods/pod-template#128]
So far the products location full path is pointing to path like: ...Build/Products/Debug/MyPod.framework

But nowadays Xcode uses Debug-iphoneos or Debug-iphonesimulator instead. Which causes the product is always red in Xcode (means not found).

Considering the Xcode itself set product location using Debug-iphoneos, could CocoaPods targets use Debug-iphoneos instead of Debug?

**Comment by orta** [comment]
Can you please make this on CocoaPods/CocoaPods - https://github.com/CocoaPods/CocoaPods/issues/

It sounds like a good fix

**Comment by pinxue** [comment]
OK. I have a wrong guess that it is related to the template.
