### ISSUE TITLE
xcode7 support

### ISSUE THREAD

**Issue by fewspider** [CocoaPods/pod-template#130]
i got a error
```
/Users/fewspider/Workspace/person/i-want-to-do/FFSideMenu/Example/Tests/Tests.swift:3:8: Module file's minimum deployment target is ios9.0 v9.0: /Users/fewspider/Library/Developer/Xcode/DerivedData/FFSideMenu-ehgrxdtajknzicdurqguxuloxhlo/Build/Products/Debug-iphonesimulator/FFSideMenu.framework/Modules/FFSideMenu.swiftmodule/x86_64.swiftmodule
```
it seems  a problem that open xcode 6 project in xcode7.
cc[Module file's minimum deployment target is ios9.0 v9.0](https://forums.developer.apple.com/thread/5454)

**Comment by segiddins** [comment]
I don't think this is a bug in the `pod lib create` template?

**Comment by fewspider** [comment]
@segiddins I don't know why sometimes it is ok,sometimes is failed,maybe the temp file.
But current xcode version is 7. 
It is necessary to update the pod-template file to fit xcode 7.
Convert xcode 6 project to xcode 7 project is not always succeed.
Thanks again:-)
