### ISSUE TITLE
Recommended project settings

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/pod-template#131]
Test case:

1. `pod lib create PROJECT`
2. Open XCode on the workspace
3. Product -> Run

Expected:

Builds with no errors

Actual:

A warning is generated for Pods.xcodeproj titled "Update to recommended settings"

![screen shot 2015-11-01 at 4 00 41 pm](https://cloud.githubusercontent.com/assets/382183/10871382/523e5e14-80b3-11e5-8c56-1649aeebe7b2.png)

**Comment by fulldecent** [comment]
Reported upstream to https://github.com/CocoaPods/Xcodeproj/issues/370 but also keeping here as there may be other related problems.

**Comment by orta** [comment]
This project uses a vendored Xcode project, so those changes would need to be done manually in here, by editing the Xcode projects by hand [objc](https://github.com/CocoaPods/pod-template/tree/master/templates/ios/Example) / [swift](https://github.com/CocoaPods/pod-template/tree/master/templates/swift/Example)

**Comment by fulldecent** [comment]
I tried doing this, but some of the specific code is created by Xcodeproj. Example:

 * Single quotes vs. double quotes

**Comment by fulldecent** [comment]
Closing, this is fixed as of CocoaPods 1.0.1.
