### ISSUE TITLE
Enable "Gather coverage data" in example app and pod framework

### ISSUE THREAD

**Issue by ZevEisenberg** [CocoaPods/pod-template#135]
I was asked to submit a PR by @segiddins [here](https://github.com/CocoaPods/CocoaPods/issues/3706#issuecomment-156587575). Any reason not to just enable it for the default project through `pod lib create`? It could be made an option, but I don't know of any downsides to just enabling coverage all the time, and making the pod a build dependency of the example project.

**Comment by orta** [comment]
I think that's a good idea for this :+1:

**Comment by fulldecent** [comment]
PR to fix master: #181

Commit to fix in hopefully-will-be-dev-real-soon: eb0828976581d671a718f3dd3cb161a4f8555df5
