### ISSUE TITLE
xcodebuild from root directory doesn't work with CocoaPods 0.36 or higher

### ISSUE THREAD

**Issue by timbodeit** [CocoaPods/pod-template#138]
pod-template installs a symlink named `_Pods.xcodeproj` pointing to `Example/Pods/Pods.xcodeproj`.

After reading the [Quality Index Guide](https://guides.cocoapods.org/making/quality-indexes), I assume this is to allow building the framework through a `xcodebuild` call from the root directory.

This works fine until CocoaPods 0.35, but projects generated by all later versions fail.

The error messages vary slightly by CocoaPods version, project language and `use_frameworks!` usage, but all include something similar to this:  
`
The file “Pods-ObjcTestLib_Example-ObjcTestLib-Private.xcconfig” couldn’t be opened because there is no such file. (/Users/timbodeit/Example/Pods/Target Support Files/Pods-ObjcTestLib_Example-ObjcTestLib/Pods-ObjcTestLib_Example-ObjcTestLib-Private.xcconfig)
`

What happens is, that paths relative to the project are resolved relative to the symlink location in the root directory instead of the location of the actual project it's pointing to.

I've reproduced this with the current pod-template master, Xcode 7.0.1 and various Versions of CocoaPods between `0.36.0.beta.1` and `0.39`.

**Comment by orta** [comment]
So this is when you just run `xcodebuild` ?

**Comment by fulldecent** [comment]
Note: AlamoFire uses a xcodeproj and xcworkspace in the root folder and it does not use a symlink.

I recommend we follow AlamoFire's example as closely as possible.

**Comment by fulldecent** [comment]
This issue would be fixed by #157

**Comment by jugutier** [comment]
@timbodeit could you verify that this still happens with `cocoapods 1.2.0` and the latest in this repository? 

We also need to know which command triggers this error.

The reason for this simlink is to allow Carthage support not for building with `xcodebuild` (afaik)

**Comment by fulldecent** [comment]
Closing now for lack of information. Please provide the requested information if available and we can reopen.
