### ISSUE TITLE
pod lib create missing LaunchScreen

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/pod-template#139]
Hi, using `pod lib create` with Example demo option will create a project, but it misses the `LaunchScreen.storyboard`. And that will cause http://stackoverflow.com/questions/32641240/ios-9-xcode-7-application-appears-with-black-bars-on-top-and-bottom

I'm on Xcode 7.1, Cocoapods 0.39.0

**Comment by orta** [comment]
I've just ran through the default install and I got a launch screen as expected. Is there anything custom in your setup?

![screen shot 2015-12-13 at 1 54 12 pm](https://cloud.githubusercontent.com/assets/49038/11768628/0798c69c-a1a1-11e5-9687-988353ab5640.png)

**Comment by onmyway133** [comment]
@orta thanks. I can't reproduce that problem. Not sure what went wrong that time. I 'll reopen issue if I meet that again
