### ISSUE TITLE
Swift is not supported for static libraries

### ISSUE THREAD

**Issue by onmyway133** [CocoaPods/pod-template#140]
I'm on Xcode 7.1 and Cocoapods 0.39.0

I run `pod lib create MyLib`, it wend fine, `pod install` on the Example project, and then open `MyLib.xcworkspace`

But then when building the Example target, I get `Swift is not supported for static libraries`

Restarting Xcode fixes the issue for me. Just wonder

**Comment by segiddins** [comment]
What options do you specify when running `pod lib create`?

**Comment by onmyway133** [comment]
@segiddins I just run `pod lib create MyLib`

**Comment by segiddins** [comment]
Right, but `pod lib create` then asks a bunch of questions, what did you answer for them?

**Comment by onmyway133** [comment]
@segiddins I choose Swift, Demo application, No for Quick and No for UI tests

**Comment by orta** [comment]
I've just ran through the entire thing with the exact same answers and got a working build.

![screen shot 2015-12-13 at 1 52 13 pm](https://cloud.githubusercontent.com/assets/49038/11768617/c7a4eeda-a1a0-11e5-85a0-13c6769d8ae3.png)

Anything else you can think of @onmyway133 ?

**Comment by onmyway133** [comment]
@orta thanks for checking. I only meet that problem once, restarting Xcode fixes the issue for me. Don't know if that is anything related to Xcode caching or not

**Comment by onmyway133** [comment]
Sometimes I get it, a `pod install` always helps

**Comment by Zhukn1** [comment]
I've just caught this with the answers:
Swift, No, None, No.

Neither `pod install` nor restarting Xcode helps.

The Podfile is generated with the `use_frameworks!` flag and I can't find the issue.

**Comment by orta** [comment]
Calling this an Xcode bug
