### ISSUE TITLE
 Use of unresolved identifier 'ABXXXView' which under:'Pods/Development Pods/MyLibrary/pod/Classes/

### ISSUE THREAD

**Issue by williamhqs** [CocoaPods/pod-template#141]
I want to make an example after i created my own lib by ```pod lib create MyLibrary```.
By i got the error ``` Use of unresolved identifier 'ABXXXView' ```, ABXXXView is the class replaced 'Pods/Development Pods/MyLibrary/pod/Classes/ReplaceMe.swift"

My steps:
**Step1** ``'pod lib create MyLibrary```

**Step2** answers ```Swift```, ```Quick```, with ```UI test``` and Example project created

**Step3** Created my own class ```ABXXXView``` to replace the default in ```Pods/Development Pods/MyLibrary/pod/Classes/ReplaceMe.swift```

Then in ViewController.swift
```    
import MyLibrary
    class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        let vi = ABXXXView()
        self.view.addSubview(vi) 
    }
}
```
I got the error as title mentioned. but i have imported MyLibrary.

**EDIT**: If i recreated a project with Objc language, everything works fine.

**Comment by segiddins** [comment]
What's the contents of your podspec?

**Comment by orta** [comment]
Didn't this get fixed somewhere else? I think this was that the class from the library was not public

**Comment by orta** [comment]
Yep: https://github.com/CocoaPods/CocoaPods/issues/4657#issuecomment-164256041
