### ISSUE TITLE
Latest Swift syntax

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/pod-template#142]
When using `pod lib create NewLib` and opening the project in XCode, I am prompted to update to the latest Swift syntax.

![screen shot 2015-12-20 at 10 15 51 pm](https://cloud.githubusercontent.com/assets/382183/11923935/5a2d8ab6-a767-11e5-82de-3f84078288c2.png)

**Comment by orta** [comment]
I think we need to change this: https://github.com/CocoaPods/pod-template/blob/master/templates/swift/Example/PROJECT.xcodeproj/project.pbxproj#L168 to the latest version

**Comment by kylef** [comment]
> I think we need to change this: https://github.com/CocoaPods/pod-template/blob/master/templates/swift/Example/PROJECT.xcodeproj/project.pbxproj#L168 to the latest version

Should probably re-generate the whole project file, I think there we're other changes in Xcode 7 build settings.
