### ISSUE TITLE
Quotes inconsistency between cocoapods.org and pod-template

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/pod-template#145]
https://cocoapods.org uses `pod 'AFNetworking', '~> 3.0'`.
pod-template uses `pod "${POD_NAME}", :path => "../"`.

Could we align with everybody using either `'` or `"`?

**Comment by Coeur** [comment]
Reading the difference between single quotes and double quotes, we should probably align with single quotes: http://stackoverflow.com/questions/6395288/double-vs-single-quotes

**Comment by segiddins** [comment]
Closed by #146.
