### ISSUE TITLE
Out of the box Swift projects causes xcodebuild to not report test summary

### ISSUE THREAD

**Issue by hwaxxer** [CocoaPods/pod-template#149]
Steps to reproduce using `Xcode 7.3`:

1. Start repo using `pod lib create test`
2. Run tests using `xcodebuild -workspace Example/test.xcworkspace -scheme test-Example test -sdk iphonesimulator`
3. The result is: `** TEST FAILED **` but there's no information about which tests failed etc.

This unfortunately also causes `xctool` to report results as failing (even if all tests passed).

**Comment by segiddins** [comment]
Do you know which test options you specified when running `pod lib create`?

**Comment by hwaxxer** [comment]
Sure, I can reproduce this 100% using Xcode `7D175`.

    $ pod lib create NoTestSummary

```
What language do you want to use?? [ ObjC / Swift ]
 > Swift
Would you like to include a demo application with your library? [ Yes / No ]
 > yes
Which testing frameworks will you use? [ Quick / None ]
 > quick
Would you like to do view based testing? [ Yes / No ]
 > no
```

    $ cd NoTestSummary; 
    $ xcodebuild test -workspace ./Example/NoTestSummary.xcworkspace -scheme NoTestSummary-Example -sdk iphonesimulator

```....
** TEST FAILED **
```

**Comment by segiddins** [comment]
Awesome, thanks! That should make it pretty easy for someone to debug by diffing the generated test files with what Xcode generates.

**Comment by hwaxxer** [comment]
Took a stab at it myself and it seems to work after a few failed attempts. :smile:
