### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/pod-template#153]
Let's be honest, lots of people that author for CocoaPods will also consider being compatible with Carthage. Currently I am also working on a "pod-template" for Carthage. 

Perhaps we can make this CocoaPods/pod-template repository support Carthage by default and be so delightful that all iOS framework authors will want to use THIS template.

**Comment by orta** [comment]
It supports Carthage by default, and has done for a long time

**Comment by orta** [comment]
Introduced in https://github.com/CocoaPods/pod-template/pull/106 - if it's broken, then I'd consider that a bug :+1:

**Comment by fulldecent** [comment]
Thanks for the heads up. Looks like I'm the bug.

Hoping to help other people with a documentation update in #154.
