### ISSUE TITLE
Set :share_schemes_for_development_pods in the 1.0 Podfile by default

### ISSUE THREAD

**Issue by orta** [CocoaPods/pod-template#169]
https://github.com/CocoaPods/CocoaPods/pull/5254 allows us to add Carthage support without having to annoy users of development Pods. We should use this in the new template.

**Comment by fulldecent** [comment]
This is achieved automatically in AlamoFire and in #179.

**Comment by fulldecent** [comment]
Closing, this was fixed in #179
