### ISSUE TITLE
Add a check for 1.0 in the configure script, and recommend updating if 0.39

### ISSUE THREAD

**Issue by orta** [CocoaPods/pod-template#170]
The Podfile won't compile, so it won't work anyway. Potentially offer a workaround via a fork?

**Comment by orta** [comment]
This doesn't look feasible without changes in CocoaPods, or ugly hacks we shouldn't use.

**Comment by segiddins** [comment]
@orta we can add a check in the podfile to raise a helpful error if the CocoaPods version is less than 1 and reccomend upgrading?

**Comment by orta** [comment]
Yeah, that might be a better call 👍

**Comment by fulldecent** [comment]
-1 This means all new pods by default (everyone uses this template) will have this new backwards compatibility check.

The upgrade warnings in `pod` proper should be sufficient.

**Comment by orta** [comment]
Aye, I think that's reasonable.
