### ISSUE TITLE
Undefined symbols for architecture x86_64:

### ISSUE THREAD

**Issue by LX314** [CocoaPods/pod-template#174]
Hello,when i use this object,if all files in my library are my self. there is nothing happened.but when i add some thrid-party projects using Cocoapods via podfile,e.g.AFNetworking,there has been some errors,just like this:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LXTool", referenced from:
      objc-class-ref in LXViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

how can i resolve this problem?

**Comment by orta** [comment]
You should probably be adding them via the Podspec https://guides.cocoapods.org/syntax/podspec.html#dependency
