### ISSUE TITLE
pod lib create: class prefix question could specify the prefix is for the example project not the lib

### ISSUE THREAD

**Issue by malhal** [CocoaPods/pod-template#177]
When you use `pod lib create` one of the questions is for the class prefix. You would assume this prefix is for the lib but in fact it is for the example. If the developer enters the same class prefix as they intend to use in their lib then that could cause a serious problem if they have a class with same name in the lib and in the example.

To solve this the question should be, `please enter a class prefix for the example project`. It should also allow pressing enter with no prefix entered. Since most of the time people don't use prefixes in an app project. 

Current workaround is to enter `My` for the prefix, which gives MyAppDelegate and MyViewController. If wanting to tidy it up then it can simply be deleted from both files and the class names, and also deleted in the project class prefix setting. Then everything is back to normal.

**Comment by malhal** [comment]
I should probably add that class prefixes are per app not per developer, according to Apple. 

https://developer.apple.com/library/ios/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Conventions/Conventions.html
"As an example, if your company were called Whispering Oak, and you were developing a game called Zebra Surprise, you might choose WZS or WOZ as your class prefix."

**Comment by orta** [comment]
Given that you're likely to be writing your library inside the Example project, I don't think it's too worrying that you _could_ have a different prefix between the lib / example. 

I wouldn't have a problem with a PR allowing empty prefixes for objc projects 👍

**Comment by malhal** [comment]
So the workspace contains the Pods project and the example project. The library gets written in the Pods project, not the example, since the command is about creating a lib I think its important to clarify the prefix is only for the example project.

First I need to check what is asked if you do `pod lib create` without specifying you'd like an example, never actually done that.

Then I'll do a pull request for:

1. Clarifying the class prefix is for the example project in the question text.
2. Allowing blank class prefix.

**Comment by malhal** [comment]
So when I specified no demo application I was surprised to still see the Example folder and a project that looks like the demo application but with no views etc. I now realise there is always a project with the name of the Pod and an application target is only added if you say yes to the demo application. I think the template will need a lot of work to change it to be a separate project for the demo application.
