### ISSUE TITLE
Drop support for Objective-C

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/pod-template#182]
This project is "an opinionated template for creating a Pod".

The parent project, CocoaPods has expressed an opinion that Swift is better than Objective-C.

> ... right now a Swift library represents forward thinking best practices

Source: https://guides.cocoapods.org/making/quality-indexes.html

We could remove the question of Swift / Objective-C in `pod-template` and just assume they want Swift.

**Comment by fulldecent** [comment]
Here is language data of all specs added in the past three months:

```bash
git ls-files -z | xargs -0 -n1 -I{} -- git log -1 --format='%ai {}' {} | cut -b 1-11,27-
git log --pretty=format: --name-only --since="3 months ago" > recentSpecs.txt
cut -d/ -f 2 recentSpecs.txt | grep . | sort -u > recentPods.txt
for a in $(cat recentPods.txt); do curl "http://metrics.cocoapods.org/api/v1/pods/$a" | grep -o '"language":"[^"]*"'; done > langs.txt
sort langs.txt | uniq -c
```

```
   2 "language":"Assembly"
  59 "language":"C"
  23 "language":"C++"
   1 "language":"CSS"
   1 "language":"GLSL"
   1 "language":"Groff"
  36 "language":"HTML"
  10 "language":"Java"
   6 "language":"JavaScript"
   1 "language":"Jupyter Notebook"
   3 "language":"Makefile"
2902 "language":"Objective-C"
  10 "language":"Objective-C++"
   1 "language":"Python"
  66 "language":"Ruby"
 231 "language":"Shell"
1904 "language":"Swift"
```

Not really helping my case. But I am looking to see if I can find all NEW pods created in the past three months.

**Comment by fulldecent** [comment]
Here is how to check all NEW pods and what language they use:

```bash
git ls-tree --name-only HEAD Specs/ | head | while read file
do
    HASH=`git rev-list HEAD $file | tail -n 1`
    DATE=`git show -s --format="%ci" $HASH --`
    echo "$DATE $file"
done > podDates.txt
grep 2016 podDates.txt | cut -b33- > recentPods.txt
for a in $(cat recentPods.txt); do curl "http://metrics.cocoapods.org/api/v1/pods/$a" | grep -o '"language":"[^"]*"'; done > langs.txt
sort langs.txt | uniq -c
```

Unfortunately, I can't run this because actually git is pretty slow with these commands :-(

**Comment by orta** [comment]
I'm not convinced I'm afraid, a quick look through the db ordered by created at for the last days shows Obj-C still user mode often than Swift - think it would be short-sighted to remove support.

![Uploading Screen Shot 2016-06-29 at 8.51.36 AM.png…]()
