### ISSUE TITLE
What language do you want to use ?  There is a bug

### ISSUE THREAD

**Issue by LazyJiu** [CocoaPods/pod-template#184]
What language do you want to use?? [ Swift / ObjC ]
 > objc   
/Users/shibin/Desktop/MandalatApiManager/configurator/TemplateConfigurator.rb:48:in `run': uninitialized constant Pod::TemplateConfigurator::ConfigureObjC (NameError)
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

If I choose swift,  it will not go wrong.

**Comment by chenvd** [comment]
+1

**Comment by ChasonTang** [comment]
Yeah,everything is ok yesterday.However,it is goes wrong Today

**Comment by Moskacz** [comment]
There is no such file as ConfigureObjc.rb in configurator directory

**Comment by ChasonTang** [comment]
https://github.com/CocoaPods/pod-template/commit/ad29704ef3a16deef79e35edecec6c523f2b84e6
this PR remove ConfigureIOS.rb file and change
```
ConfigureIOS.perform(configurator: self)
```
to
```
ConfigureObjC.perform(configurator: self)
```
so the crash happen

**Comment by thierryxing** [comment]
+1

**Comment by Monkshae** [comment]
+1

**Comment by CoderAFI** [comment]
+1

**Comment by orta** [comment]
Sorry about that, work on v2 that shouldn't have been made public yet - I've moved it back to the old version 👍

**Comment by fulldecent** [comment]
So sorry about this everyone. My bad here!
