### ISSUE TITLE
MyLib.xcodeproj does NOT get generated with pod lib create MyLib

### ISSUE THREAD

**Issue by rcholic** [CocoaPods/pod-template#188]
I am following [[this tutorial here]](https://guides.cocoapods.org/making/using-pod-lib-create)  to create my first CocoaPod library (e.g. named `MyLib`), but after I executed the commands, I don't see my library created with the file structures they described on the tutorial.

For example, I don't see `MyLib.xcodeproj` in the root folder `MyLib`, instead I see `_Pods.xcodeproj`; there is no `Pods` directory, although the tutorial says so. 

I did this command for linting `pod lib lint MyLib.xcodespec --allow-warnings` and `pod lib lint --allow-warnings`. 

The results of both commands is **MyLib passed validation.**

In the `MyLib.xcodespec` file, I have the following dependencies: 

```
    s.dependency 'SCSiriWaveformView', '~> 1.0.3'
      s.dependency 'SnapKit', '~> 0.22.0'
      s.dependency 'FDWaveformView', '~> 1.0.1'
```

Should I rename `_Pods.xcodeproj` to `MyLib.xcodeproj` so I can write my source code in the directory?

**Comment by jaenthemaen** [comment]
Same here. I am slightly confused as well regarding the project structure created by pod lib create with the standard template, especially the _Pods.xcodeproj part.

**Comment by jugutier** [comment]
@jaenthemaen the _Pods.xcodeproj is a symlink to the original xcode projcet (i.e a shortcut) so that your pods are compatible with Carthage.

**Comment by jugutier** [comment]
@rcholic is this still an issue? can you post more information as your pod version, which options you passed in and your directory structure after finishing the wizard? Thanks

**Comment by fulldecent** [comment]
Closing as unresponsive. Please add details if this is still an issue and we can quickly reopen.
