### ISSUE TITLE
`pod lib create` git clone  should add flag --depth=1

### ISSUE THREAD

**Issue by AntiMoron** [CocoaPods/pod-template#192]
as post title.

**Comment by orta** [comment]
This is a good idea 👍

**Comment by orta** [comment]
You're welcome to take a stab at it in CocoaPods, where the work is done

**Comment by AntiMoron** [comment]
ok . @orta

**Comment by jugutier** [comment]
This issue belongs to CocoPods. Closing this for now, please reopen if there's any work that needs to happen here also in order to support it.
