### ISSUE TITLE
'pod lib create' creates a pod project without given name

### ISSUE THREAD

**Issue by ccwinner** [CocoaPods/pod-template#195]
For example, 'pod lib create foo' aims to create a pod project starts with name 'foo', but the podspec file name is  'NAME', and the name of xcode file in ios/Example/ is 'PROJECT'. What should I do to change the whole project name to be 'foo'?

**Comment by fulldecent** [comment]
Hm... could you please paste full console output. Is anyone else seeing this too?

**Comment by ccwinner** [comment]
Cloning `https://github.com/CocoaPods/pod-template.git` into `LJMPushSDK`.
Configuring LJMPushSDK template.
! Before you can create a new library we need to setup your git credentials.

 What is your name?
 > chenxiao

! Setting your name in git to chenxiao
  git config user.name "chenxiao" 
What is your email?
 > chenxiao@lianjia.com

! Setting your email in git to chenxiao@lianjia.com
  git config user.email "chenxiao@lianjia.com"

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > Yes

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > Yes

What is your class prefix?
 > LJM

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

**Comment by ccwinner** [comment]
I reinstalled cocoapods, and the problem was solved. (⊙o⊙)… pod version updated from 1.0.1 to 1.1.1.

**Comment by ko0f** [comment]
Happens here as well. Got version 1.1.1 installed on macOS, tried reinstalling - didn't help.

**Comment by ko0f** [comment]
With the prerelease version `1.2.0.beta.1` it works.

**Comment by jugutier** [comment]
Should this be closed @ccwinner ?
When trying to reproduce in my env:

pod lib create
[!] A name for the Pod is required.

using cocoapods 1.1.1

**Comment by ccwinner** [comment]
@jugutier Sure. But it'd be better to get the reason

**Comment by jugutier** [comment]
@ccwinner absolutely. When trying to run the command above I couldn't reproduce (version 1.1.1, now I'm on 1.2.0pre). You're not adding the initial command in your comment with your console output. Could you add more information?

**Comment by ccwinner** [comment]
@jugutier The problem can not be reproduced since I updated the pod. The initial command is 'pod lib create LJMPushSDK'. I made a test on another device with pod v1.0.1, which worked as well. But I found there were some difference in the final command lines.

From  my previous one is 
"**To learn more about the template see https://github.com/CocoaPods/pod-template.git.
To learn more about creating a new pod, see http://guides.cocoapods.org/making/making-a-cocoapod.**" 

while normal is
"Running pod install on your new library.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
[!] No `Podfile' found in the project directory.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'LJMTestDemo/Example/LJMTestDemo.xcworkspace'
The file /Users/zhangxiaolong/Downloads/LJMTestDemo/Example/LJMTestDemo.xcworkspace does not exist.

**To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod**`.
zhangxiaolongdeMacBook-Pro:Downloads zhangxiaolong$ pod --version
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
1.0.1"

I argue that the problem happens when it does not run 'pod install' after answering a few questions in command.

**Comment by jugutier** [comment]
@ccwinner 
`warning: insecure world...` is a [permissions error](http://stackoverflow.com/questions/3952243/warning-insecure-world-writable-dir-usr-local-bin-in-path-mode-040777) 

It is a breaking change OSX called [system integrity](https://support.apple.com/en-us/HT204899) which prevents installing gems in the shared ruby repository. 

This is fixed by installing the gems locally to your context with `bundle exec`, as you well said this happens behind the curtains and is now fixed in the new version.

I believe this issue either belongs to cocoapods or needs to be closed because it's not happening anymore. 

-J

**Comment by ccwinner** [comment]
Thanks for help,  I will close this issue as no similar problem happens since the new version of cocoapods installed.
