### ISSUE TITLE
'Profile' in the .gitignore

### ISSUE THREAD

**Issue by ccloong** [CocoaPods/pod-template#205]
Hi,

Is there any reason to define 'Profile' in the .gitignore?
As I use the template to create a private pod project, and I have a directory named 'Profile' by chance. It makes git ignore the whole directory...
I think 'Profile' is a pretty ordinary name, so it is possible for others to run into this problem too.
If somebody is migrating exists project into a new created(by using pod lib create) one, and it happened that a directory named 'Profile' included, it may cause some issues.

**Comment by orta** [comment]
You're welcome to send a PR, looks like it was removed from https://github.com/github/gitignore/blob/master/Objective-C.gitignore where we originally got it

**Comment by ccloong** [comment]
Thanks to reply, I'll close the issue then.
