### ISSUE TITLE
pod lib create podTestLibrary command failed

### ISSUE THREAD

**Issue by aaronSwift123** [CocoaPods/pod-template#209]
pod lib create podTestLibrary command failed with message:

`Cloning `https://github.com/CocoaPods/pod-template.git` into `podTestLibrary`.
Configuring podTestLibrary template.
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- colored2 (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/aaron/Desktop/podTestLibrary/setup/TemplateConfigurator.rb:2:in `<top (required)>'
	from ./configure:5:in `require_relative'
	from ./configure:5:in `block in <main>'
	from ./configure:4:in `each'
	from ./configure:4:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.`

**Comment by segiddins** [comment]
What version of cocoapods are you using?

**Comment by aaronSwift123** [comment]
@segiddins 1.2.0

**Comment by liulishuo** [comment]
Me too.
No such problem yesterday.

**Comment by liulishuo** [comment]
@aaronSwift123 update to version 1.2.1 is ok

**Comment by skensell** [comment]
Happening to me too with 1.1.1 today. I will upgrade and see if it helps.

**Comment by skensell** [comment]
Upgrading to 1.2.1 did indeed work.

**Comment by orta** [comment]
I wonder if the pod-template can work with both `colored` and `colored2`
