### ISSUE TITLE
Using pod lib create causes unit tests to not run

### ISSUE THREAD

**Issue by nneuberger1** [CocoaPods/pod-template#223]
I'm opening another ticket because I'm trying to figure out why unit tests don't run after creating a brand new Pod Project via the following command:

`pod lib create PodExample`

It's related to this ticket possibly.
https://github.com/CocoaPods/pod-template/issues/114

I created a simple method in the ReplaceMe.swift and then added a new Unit Test class and ran things.

Any ideas what the problem is?   Is this possibly a @testable import issue?

**Comment by teameh** [comment]
Same here, I got: 

![picture 2018-07-18 at 14 18 12](https://user-images.githubusercontent.com/1330668/42880703-75a1859a-8a95-11e8-97b3-2d3d56dd3c6b.jpg)

This fixed the issue for me: https://stackoverflow.com/a/45020256/672989

**Comment by amorde** [comment]
I believe this was fixed in #229 - can anyone confirm?

**Comment by jugutier** [comment]
Closing this as fixed by #229. If this is still an issue please reopen cc: @nneuberger1 @teameh
