### ISSUE TITLE
create lib fail in V1.5.2

### ISSUE THREAD

**Issue by LoseAnson** [CocoaPods/pod-template#225]
test pod lib create LALib
Cloning `https://github.com/CocoaPods/pod-template.git` into `LALib`.
Configuring LALib template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - https://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )

What platform do you want to use?? [ iOS / macOS ]
 > iOS

What language do you want to use?? [ Swift / ObjC ]
 > Objc

Would you like to include a demo application with your library? [ Yes / No ]
 > YES

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > No

Possible answers are [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > LA
Traceback (most recent call last):
	21: from ./configure:9:in `<main>'
	20: from /Users/loseanson/Desktop/test/LALib/setup/TemplateConfigurator.rb:85:in `run'
	19: from /Users/loseanson/Desktop/test/LALib/setup/ConfigureiOS.rb:7:in `perform'
	18: from /Users/loseanson/Desktop/test/LALib/setup/ConfigureiOS.rb:73:in `perform'
	17: from /Users/loseanson/Desktop/test/LALib/setup/ProjectManipulator.rb:30:in `run'
	16: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	15: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	14: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	13: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	12: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	11: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	10: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 9: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 8: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	 7: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 6: from /Users/loseanson/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	 5: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	 4: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	 3: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	 2: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	 1: from /Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
/Users/loseanson/.rvm/gems/ruby-2.5.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x00007fc1d70b3fb0> (NoMethodError)
Did you mean?  to_s

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
➜  test

**Comment by segiddins** [comment]
This is a bug in Xcodeproj that has been fixed on master

**Comment by zhenxiaobin** [comment]
Hello. How this problem is solved, please provide some solutions.thanks

**Comment by jugutier** [comment]
This error pertains to xcodeproj and has been fixed in master. Because a new version of xcodeproj hasn't yet been released you would still continue to experience the error until that happens.

If you can't wait for the next release I would suggest you clone the xcodeproj repo and build locally with the fix

1. Clone this repo https://github.com/CocoaPods/Xcodeproj
2. `gem build xcodeproj.gemspec`
3. `sudo gem install ./xcodeproj-<version>.gem`

Hope this helps.

**Comment by dnkoutso** [comment]
Xcodeproj 1.5.9 has been released that includes this hot fix.

**Comment by jugutier** [comment]
Awesome @dnkoutso . 

I will close this issue then. 

@LoseAnson Feel free to reopen  if it persists after upgrading.
