### ISSUE TITLE
create lib fail in V1.5.8

### ISSUE THREAD

**Issue by zhenxiaobin** [CocoaPods/pod-template#227]
xiaobin:Desktop zhenxb$ pod lib create HKLib
Cloning `https://github.com/CocoaPods/pod-template.git` into `HKLib`.
Configuring HKLib template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - https://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )

What platform do you want to use?? [ iOS / macOS ]
 > iOS

What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > NO

What is your class prefix?
 > HK
/Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x007ff3c39544a8> (NoMethodError)
Did you mean?  to_s
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/Desktop/HKLib/setup/ProjectManipulator.rb:30:in `run'
	from /Users/zhenxb/Desktop/HKLib/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/zhenxb/Desktop/HKLib/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/zhenxb/Desktop/HKLib/setup/TemplateConfigurator.rb:85:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

xiaobin:Desktop zhenxb$ pod --version
1.5.2
xiaobin:Desktop zhenxb$ Xcodeproj --version
1.5.8
xiaobin:Desktop zhenxb$

**Comment by zhenxiaobin** [comment]
zhenxiaobin:工具库 zhenxb$ git clone https://github.com/CocoaPods/Xcodeproj
Cloning into 'Xcodeproj'...
remote: Counting objects: 13373, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 13373 (delta 1), reused 5 (delta 1), pack-reused 13363
Receiving objects: 100% (13373/13373), 3.40 MiB | 14.00 KiB/s, done.
Resolving deltas: 100% (8229/8229), done.
zhenxiaobin:工具库 zhenxb$ gem build xcodeproj.gemspec
ERROR:  Gemspec file not found: xcodeproj.gemspec
zhenxiaobin:工具库 zhenxb$ cd Xcodeproj/
zhenxiaobin:Xcodeproj zhenxb$ gem build xcodeproj.gemspec
  Successfully built RubyGem
  Name: xcodeproj
  Version: 1.5.8
  File: xcodeproj-1.5.8.gem
zhenxiaobin:Xcodeproj zhenxb$ sudo gem install ./xcodeproj-.gem
Password:
ERROR:  Could not find a valid gem './xcodeproj-.gem' (>= 0) in any repository
ERROR:  Possible alternatives: xcodeproj, xcodeproj-sort, xcodeproj_merge, xcodeproject
zhenxiaobin:Xcodeproj zhenxb$ sudo gem install ./xcodeproj-1.5.8.gem
Successfully installed xcodeproj-1.5.8
Parsing documentation for xcodeproj-1.5.8
Done installing documentation for xcodeproj after 1 seconds
1 gem installed
zhenxiaobin:Xcodeproj zhenxb$


zhenxiaobin:~ zhenxb$ cd /Users/zhenxb/Desktop/APP/工具库; clear; pwd
/Users/zhenxb/Desktop/APP/工具库
zhenxiaobin:工具库 zhenxb$ pod lib create aaadhk
Cloning `https://github.com/CocoaPods/pod-template.git` into `aaadhk`.
Configuring aaadhk template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - https://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )


What platform do you want to use?? [ iOS / macOS ]
 > iOS

What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > HK
/Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:27:in `<module:BuildSettingsArraySettingsByObjectVersion>': undefined method `to_set' for #<Array:0x007f80ae958568> (NoMethodError)
Did you mean?  to_s
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:8:in `<class:XCBuildConfiguration>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:4:in `<module:Object>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:3:in `<class:Project>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:2:in `<module:Xcodeproj>'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/helpers/build_settings_array_settings_by_object_version.rb:1:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object/build_configuration.rb:194:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project/object.rb:521:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/gems/ruby-2.4.1/gems/xcodeproj-1.5.8/lib/xcodeproj/project.rb:5:in `<top (required)>'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zhenxb/Desktop/APP/工具库/aaadhk/setup/ProjectManipulator.rb:30:in `run'
	from /Users/zhenxb/Desktop/APP/工具库/aaadhk/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/zhenxb/Desktop/APP/工具库/aaadhk/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/zhenxb/Desktop/APP/工具库/aaadhk/setup/TemplateConfigurator.rb:85:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
zhenxiaobin:工具库 zhenxb$

**Comment by zhenxiaobin** [comment]
thanks

**Comment by liuchuan-alex** [comment]
6666

**Comment by jugutier** [comment]
It would be 

sudo gem install xcodeproj-1.5.8.gem

(The local gem you just built needs to match the file name)
