### ISSUE TITLE
The unusable template was created using the command pod lib create.

### ISSUE THREAD

**Issue by Isaaclzg** [CocoaPods/pod-template#228]
The unusable template was created using the command ` pod lib create.`
![podlib1.png](https://upload-images.jianshu.io/upload_images/627306-d571af4023d4a608.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![podlib2.png](https://upload-images.jianshu.io/upload_images/627306-8d3e01cb6a62b00d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

Mac：10.13.4
Xcode：9.3.1
CocoaPods:1.5.2
PS: before no problem

**Comment by jugutier** [comment]
Hello 
please update xcodeproj to version 1.5.9 and try again


sudo gem update xcodeproj
