### ISSUE TITLE
custom a new template base on this

### ISSUE THREAD

**Issue by iPermanent** [CocoaPods/pod-template#234]
I tried to create a pod template like this, clone it to my own git source, and add some file that all my pod lib need to use, however, it has the error like this
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/1712759/54484735-9d292080-48a6-11e9-9b15-109617cb3aeb.png">
I doubt where I had used the utf8 string in Chinese language, but did not find, here is my template source git, all I do is clone the code to my own.
https://gitlab.com/iPermanent/cocoapodstemplate.git

**Comment by orta** [comment]
Could be an issue with quoting?

**Comment by iPermanent** [comment]
> Could be an issue with quoting?

I had resolved it, thanks, just change the git commit info, user_name to English, it worked fine, Chinese characters will lead errors

**Comment by segiddins** [comment]
Looks like the name needed to go into a quoted, rahter than unquoted, string

**Comment by GuoZhiQiang** [comment]
Same error. Why do zh-Hans need quoted and the English characters don't need ?

**Comment by GuoZhiQiang** [comment]
Same error. Why do zh-Hans need quoted and the English characters don't need ?

**Comment by orta** [comment]
whoever built the parser for plists made that call
