### ISSUE TITLE
When I execute configure, the error is as follows

### ISSUE THREAD

**Issue by 15130886370** [CocoaPods/pod-template#249]
Traceback (most recent call last):
	6: from ./configure:4:in `<main>'
	5: from ./configure:4:in `each'
	4: from ./configure:5:in `block in <main>'
	3: from ./configure:5:in `require_relative'
	2: from /Users/qihuandiyishuai/Desktop/Lego-master/Modules/AAAAA/setup/TemplateConfigurator.rb:2:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- colored (LoadError)

**Comment by 15130886370** [comment]
How to solve this situation？Thank you

**Comment by igor-makarov** [comment]
Can you run `pod env` and paste the output?

**Comment by 15130886370** [comment]
### Stack

```
   CocoaPods : 1.9.3
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A7209)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 15130886370 - git - git@github.com:15130886370/MyModulizationDemo.git @ 5ea9c6255adf47b0816d4a508f3436fbe05a38b5

               cocoapods - git - https://github.com/CocoaPods/Specs.git @ 5805a1e472ebb868f213518240575b79a662db71

               https: - file system
               iOS_WSVersionSpec - git - https://gitlab.wsecar.cn/iostmpl/wsversionspec.git @ 2af873a034809517614a31b3cba661d1b8181f68

               MyModulizationDemo - git - https://github.com/15130886370/MyModulizationDemo.git @ 5ea9c6255adf47b0816d4a508f3436fbe05a38b5

               PrivatePods - git - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7

               trunk - CDN - https://cdn.cocoapods.org/
               wsecar-wsversionspec - git - git@gitlab.wsecar.cn:iostmpl/wsversionspec.git @ 2af873a034809517614a31b3cba661d1b8181f68

```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0

**Comment by igor-makarov** [comment]
It seems your version of `pod-template` isn't up to date. It's loading the gem `colored` which has been replaced by `colored2`. I'm gonna close this issue now as the latest version should be working.

**Comment by 15130886370** [comment]
ok, thanks
