### ISSUE TITLE
Default iOS deployment_target causes warnings in XCode 12+

### ISSUE THREAD

**Issue by zackdotcomputer** [CocoaPods/pod-template#250]
See [this issue in the Core repo](https://github.com/CocoaPods/CocoaPods/issues/9884) for the background here.

TLDR; as of xcode 12, the compiler now throws a warning for targets that target versions of iOS older than 9.0. This is an issue as the default Podspec targets 8.0, meaning most Pods cause this warning.

**Comment by dnkoutso** [comment]
sounds good yeah I think this is fine to update for newly created pods to specify minimum 9.0

**Comment by zackdotcomputer** [comment]
Great - will have a PR in like 5 minutes @dnkoutso
