### ISSUE TITLE
Adopt flat style badges

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/pod-template#44]
See http://shields.io

They rock!

**Comment by pavankataria** [comment]
Guys, for the pod version img shield, how can I change the colour of it? I understand there may be conventions in place for the colour blue to be chosen but I don't think that the majority would care if I decided to make it a bright green so it matches with my other badges. 
Hope it's possible somehow, by hook or crook. I mean, I could just create the badge myself but then the pod version number wouldn't be dynamic.. and I don't fancy having to change that version number myself repeatedly.
