### ISSUE TITLE
"Usage" section in POD_README.md should be improved

### ISSUE THREAD

**Issue by fastred** [CocoaPods/pod-template#48]
I think the **Usage** header suggests that the section is going to contain informations on how to use a project. But what's there are steps necessary to run an example project.

We could improve it in one of these ways:

* rename **Usage** to **Demo** or **Example**
* add a hint to the pod owner that he/she should include code samples in this section
* merge it with **Installation** section (it's probably a bad idea)

**Comment by fulldecent** [comment]
I agree. By the time the template is done filling the EXAMPLE section will show how to use the demo project, not the actual pod library.

Above PR fixes this.

**Comment by fulldecent** [comment]
Sorry, here is the PR 
https://github.com/CocoaPods/pod-template/pull/163
