### ISSUE TITLE
Shields.io Badges Invalid

### ISSUE THREAD

**Issue by wjk** [CocoaPods/pod-template#56]
I am creating a number of Pods using the `pod-template` repo and `pod lib create`. They are working great; however, the badges automatically placed in the README don’t say anything useful. I have long since submitted [a Pod](https://github.com/wjk/NSString-ShellSplit#nsstringshellsplit) through trunk, I have verified that it is present in the Specs repo, but the badges still say “pod invalid”. Does anyone know why this is?

**Comment by alexdoloz** [comment]
Hello, guys! I have the same issue – my pod https://github.com/cayugasoft/FreestylerCore works just fine but all badges show "pod invalid". Badges are:
[![Version](https://img.shields.io/cocoapods/v/FreestylerCore.svg?style=flat)](http://cocoapods.org/pods/FreestylerCore)
[![License](https://img.shields.io/cocoapods/l/FreestylerCore.svg?style=flat)](http://cocoapods.org/pods/FreestylerCore)
[![Platform](https://img.shields.io/cocoapods/p/FreestylerCore.svg?style=flat)](http://cocoapods.org/pods/FreestylerCore)

Do you have any ideas how to fix it?

**Comment by codytwinton** [comment]
@alexdoloz I've got the same issue. Also, my owner page doesn't show my pod: https://cocoapods.org/owners/8966

The pod I'm having issue with is here: https://cocoapods.org/pods/SwiftyVIPER

**Comment by EmilioPelaez** [comment]
@codytwinton seems like you solve this, could you share how?

**Comment by codytwinton** [comment]
@EmilioPelaez - Still having the same issue: http://stackoverflow.com/questions/40599432/cocoapods-spec-access-ownership-issue

**Comment by SebastianBoldt** [comment]
+1

**Comment by codytwinton** [comment]
Looks like an issue has been filed with the Cocoapods repo: https://github.com/CocoaPods/CocoaPods/issues/6184

Now, we wait. :D

**Comment by EmilioPelaez** [comment]
@codytwinton weird, when I saw your repo before I commented I saw the correct badges. Seems like mine are working as well now. Cheers!

**Comment by codytwinton** [comment]
Yes, the issue was resolved yesterday, I believe. This issue can be closed

**Comment by SebastianBoldt** [comment]
Works again. Thank you.
