### ISSUE TITLE
Account for invalid characters (for github repos) in pod name

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/pod-template#69]
Moved from https://github.com/CocoaPods/CocoaPods/issues/2337.

**Comment by fulldecent** [comment]
@ivanzoid could you please confirm if this is still an issue?

**Comment by fulldecent** [comment]
I have reported this issue upstream to

CocoaPods/Xcodeproj#369

Please close here.

**Comment by segiddins** [comment]
For now, we should error in the `configure` script when such an invalid character is used, until we can fix the upstream issue -- that way, its clear why things are failing.
