### ISSUE TITLE
Use Xcodeproj to generate the example (and framework) project

### ISSUE THREAD

**Issue by kylef** [CocoaPods/pod-template#78]
I think it would be nice to replace the current Example project which is just renamed to some code that can generate framework targets for all selected platforms along with test target and example target depending on the users options.

I'd suggest the new layout would look something like this (using Stencil as the name of this pod).

```
.
├── LICENSE
├── README.md
├── Stencil.podspec
├── Stencil.xcodeproj

├── Stencil
│   ├── (Shared Code).swift
│   ├── ios
│   │   ├── (iOS only code)
│   ├── osx
│   │   ├── (OSX only code)
├── StencilTests
│   ├── The tests
│   ├── ios
│   │   ├── (iOS only tests)
│   ├── osx
│   │   ├── (OSX only tests)
├── StencilExample
│   ├── Any example code
```

The project would have the following targets:

- Stencil-iOS (Framework)
- Stencil-OSX (Framework)
- Stencil-iOSTests
- Stencil-OSXTests
- Stencil-Example (Example OS X or iOS application?)

Would also have some script (Makefile, Rakefile or .travis.yml) that can build everything and run both platform tests.

**Comment by kylef** [comment]
Adding to this, it could create a [universal iOS and OS X framework](https://github.com/kylef/URITemplate.swift/commit/fb2b6d561a232466a66a553feae77a24bcf9abd6) so we can put them all in one target.

Example: https://github.com/kylef/URITemplate.swift

**Comment by kylef** [comment]
Depends on: https://github.com/CocoaPods/Xcodeproj/issues/227

**Comment by fulldecent** [comment]
FWIW, https://github.com/MengTo/Spring works like this proposal recommends.

**Comment by orta** [comment]
I'd much rather we re-shuffle everything to format how SwiftPM works ( this was mentioned in https://github.com/CocoaPods/pod-template/pull/152 ) so that people building pods now will get it "for free" as soon as possible

**Comment by fulldecent** [comment]
That is a way better idea. Since #78 and #152 are mutually competing and #152 has more future proofing, I recommend to close #78 at this time.

**Comment by fulldecent** [comment]
More notes coming at #152.

**Comment by orta** [comment]
:+1:
