### ISSUE TITLE
new .travis.yml file passes on a fail

### ISSUE THREAD

**Issue by orta** [CocoaPods/pod-template#80]
https://travis-ci.org/orta/ar_dispatch/builds/42975318

**Comment by laptobbe** [comment]
I can confirm that @paulmelnikow suggesting fixes the issue. Just started a new project with pod lib create and build 7 is when I updated the Specta pod. <https://travis-ci.org/laptobbe/Realm-Rest/builds>

**Comment by orta** [comment]
I've pushed a build that locks us to that tag, might have to have to talk to them about getting a new podspec out

**Comment by paulmelnikow** [comment]
:+1:
