### ISSUE TITLE
`pod lib create` should offer the option to create a JSON podspec

### ISSUE THREAD

**Issue by irace** [CocoaPods/pod-template#83]
Right now it will always create a Ruby podspec. Since CocoaPods supports JSON podspecs as well, `pod lib create` should offer this functionality (I'd argue that JSON should be the default, but I wouldn't expect to win that argument, so I won't :smile:)

**Comment by orta** [comment]
I'm not gonna keep this issue around, and I don't think we should offer it as an option, because most people won't care. Ruby podspecs are more readable, and are common in nearly every repo.

**Comment by irace** [comment]
> I'm not gonna keep this issue around, and I don't think we should offer it as an option, because most people won't care. Ruby podspecs are more readable, and are common in nearly every repo.

Probably a pragmatic decision, though for me personally, JSON podspecs being a second-class citizen has been a continual source of frustration.

**Comment by segiddins** [comment]
They're not _intentionally_ second class -- when there are reported bugs, we try to fix them. But the fact of the matter is that none of the core team use them directly, and so stuff slips thru the cracks.

**Comment by irace** [comment]
> They're not intentionally second class -- when there are reported bugs, we try to fix them. But the fact of the matter is that none of the core team use them directly, and so stuff slips thru the cracks.

I hear that, it makes sense and I think in general you’ve (you specifically, but also the rest of the time) done a great job of responding to bug reports.

Conversely, not supporting JSON podspecs in `pod lib create` sends a pretty strong message IMO.
