### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/pod-template#88]
- [ ] [No class prefix](https://github.com/CocoaPods/CocoaPods/issues/3013)

**Comment by kylef** [comment]
Tagging this into #78 (changing pod template to generate an Xcode framework instead of static library using Xcodeproj generation).

**Comment by orta** [comment]
this is handled in other issues, closing as dupe.

**Comment by getaaron** [comment]
@orta is there one open issue to represent this problem? The issues linked to this one are also closed.

**Comment by orta** [comment]
Yeah, I think you're right, this is separate from the frameworks

**Comment by basememara** [comment]
Step-by-step for manually creating CocoaPods in Swift: http://bit.ly/swift-cocoapods

**Comment by orta** [comment]
nice, you can also beta test by `pod lib create [libname] git@github.com:orta/pod-template.git`

**Comment by basememara** [comment]
Cool, thanks for doing this! I just tried it out and it's a great start. I don't know Ruby or Xcode scripting so I wish I can help more, but my feedback is to hopefully copy the structure of [SwiftyJSON's CocoaPod](https://github.com/SwiftyJSON/SwiftyJSON) instead, [Alamofire](https://github.com/Alamofire/Alamofire) is just about the same too. See the screenshot below with your template on the left and SwiftyJSON on the right.

![capturfiles_99](https://cloud.githubusercontent.com/assets/892152/7517691/858ab042-f4a4-11e4-81a4-4cfc7540741b.png)

**Comment by orta** [comment]
If you're writing swift then you are more or less fluent in ruby.

I digress though, baby steps, that can be an end-game, but for now I'm doing the equivalent of the Obj-C one with Swift support.

**Comment by orta** [comment]
OK frameworks support is in.

**Comment by basememara** [comment]
It works beautifully and the structure is so clean, great work! Thanks a mil!!! :+1:

**Comment by orta** [comment]
:+1:  ace
