### ISSUE TITLE
Specta test fails

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/pod-template#96]
The default provided Test.m file produces failures:

> Type name required...

![screen shot 2015-03-16 at 6 40 27 pm](https://cloud.githubusercontent.com/assets/382183/6678025/ed276fae-cc0b-11e4-97c1-35d7ae71cea0.png)

**Comment by orta** [comment]
ouhhh, yeah, I do believe we've changed the syntax around `AsyncBlock`. I'll update, thanks @fulldecent

**Comment by orta** [comment]
Thanks - https://github.com/CocoaPods/pod-template/commit/ac3153b6f0d42565235361b9f52dafd5a33b31e5
