### ISSUE TITLE
Remove the class prefix option for frameworks

### ISSUE THREAD

**Issue by orta** [CocoaPods/pod-template#97]
I think it's not quite the right move to do it for all projects, a quick look though CocoaPodsFeed shows that most Objective-C libs are still prefixing, and given our containers, they should be.

**Comment by SpacyRicochet** [comment]
Shouldn't Swift projects still have prefixes for frameworks? If you combine two similar Pods in one project, you might end up with classes that have the same name. Not sure how that would work when calling them in code.

**Comment by orta** [comment]
Nope, that's totally fine in frameworks-land. You can just be more specific about where it comes from. :+1:

**Comment by orta** [comment]
This is in.
