### ISSUE TITLE
Include a Code of Conduct?

### ISSUE THREAD

**Issue by orta** [CocoaPods/pod-template#98]
http://contributor-covenant.org

**Comment by segiddins** [comment]
:+1:, but it needs to be opt-in for it to have any meaning

**Comment by fulldecent** [comment]
This PR matches the policy of https://github.com/CocoaPods/CocoaPods

**Comment by fulldecent** [comment]
:-1 `pod-template` project scope is to include things that are a "very strongly encouraged best practice".

Personally, including CoC seems more like a meme than progressing computer science. But from a more facts-based approach, CoC is *way* too new to be considered on the same grounds as unit testing.
